### ISSUE TITLE
Add an open-source license

### ISSUE THREAD

**Issue by sjaustirni** [kayak233/crayon#4]
Hi!
Long story short, I really like crayon so far, especially the fact that it does not require SDL to work and would like to contribute to it in the future (as well as use it in my own projects).
Since crayon has been so kindly put on GitHub, I assume there's a chance it is meant to be an opensource project. If it is so, could an opensource license be put in the repository?

**Comment by kayak233** [comment]
Sorry for this late reply, I was stuck in my daily works for last few months. The development will be continued, and `Apache-2.0` will be added as an open-source license asap.

BTW, i don't think `crayon` is stable enough to be used in any real-world development.

**Comment by sjaustirni** [comment]
Thank you!
I surely plan to contribute to the project.
Yes, I do acknowledge the fact that crayon is not production-ready yet. The fun is in making it production-ready :D
